name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Preparar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Verificar versiones
        run: |
          node --version
          npm --version

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar aplicacion
        run: npm run build