name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-test:
    name: CI - Build and Validate
    runs-on: self-hosted

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Preparar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Verificar versiones
        run: |
          node --version
          npm --version

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar aplicacion
        run: npm run build


  deploy:
    name: CD - Deploy to DM-API-01
    runs-on: self-hosted
    needs: build-test

    steps:

      - name: Desplegar aplicacion
        run: |
          ssh alvaro@192.168.2.20 '
            set -e

            cd ~/distrito-vmware-aws

            echo "Actualizando codigo..."
            git pull origin main

            echo "Construyendo imagen Docker..."
            docker build -t distrito-miami:latest .

            echo "Actualizando contenedor..."
            docker compose up -d --force-recreate

            echo "Estado de contenedores:"
            docker compose ps
          '

      - name: Health Check
        run: |
          sleep 5
          curl --fail --retry 5 --retry-delay 3 http://192.168.2.20:3000